const prompts: string[] = [
    // Visual representation of art
    "A serene landscape inspired by the works of Claude Monet.",
    "A modern, abstract piece using bold, contrasting colors.",
    "A tranquil forest scene with dappled sunlight filtering through the trees.",
    "A vibrant cityscape at sunset.",
    "A surreal underwater world with bioluminescent creatures.",
    "A whimsical steampunk city.",
    "A futuristic metropolis with flying cars.",
    "A dreamy moonlit garden.",
    "A cosmic nebula in vivid colors.",
    "A mystical castle hidden in the clouds.",

    // Weird scenes
    "A clock melting into a stove.",
    "A genie emerging from a bottle.",
    "A warped mirror reflecting distorted faces.",
    "A carousel with mythical creatures as riders.",
    "An upside-down room with gravity-defying furniture.",
    "A floating island held up by giant balloons.",
    "A forest where trees have eyes and watchful expressions.",
    "A library where books come alive and interact with readers.",
    "A garden of oversized flowers with petals like umbrellas.",
    "A staircase that leads to different dimensions.",

    // Macro photo of brain cells or other microscopic structures
    "Close-up of intricate neural connections in the brain.",
    "A cluster of colorful neurons firing.",
    "Microscopic view of blood cells flowing through vessels.",
    "Zoomed-in image of a butterfly's delicate wing scales.",
    "Detailed shot of a spider's intricate web.",
    "A cross-section of plant cells under a microscope.",
    "The crystalline structure of a snowflake.",
    "A close look at the texture of a leaf.",
    "Magnified view of a water droplet on a surface.",
    "The intricate patterns on a butterfly's antenna.",

    // Profile picture of animals
    "A majestic lion with a regal expression.",
    "A playful puppy with floppy ears.",
    "A wise old owl perched on a branch.",
    "A curious cat peeking out from behind a curtain.",
    "A graceful swan gliding on a serene lake.",
    "A mischievous squirrel nibbling on a nut.",
    "A fluffy bunny with twitching whiskers.",
    "A colorful parrot showing off its vibrant plumage.",
    "A sleek dolphin leaping out of the water.",
    "A contented turtle basking in the sun.",

    // Distorted image of a classroom or random objects
    "A classroom reflected in a funhouse mirror.",
    "Random objects morphing into each other.",
    "A distorted view of a cluttered desk.",
    "Abstract shapes created by bending light.",
    "A kaleidoscope of everyday items.",
    "A hallway with twisted perspectives.",
    "A room seen through a glass of water.",
    "Objects refracted through a crystal prism.",
    "A distorted view of a city skyline.",
    "A twisted reflection in a polished metal surface.",

    // Image depicting the past, future, dystopia, or science fiction
    "A sepia-toned photograph of a vintage car.",
    "A futuristic cityscape with flying cars and holographic billboards.",
    "A post-apocalyptic wasteland with crumbling buildings.",
    "A time-traveling adventurer stepping out of a portal.",
    "A cybernetically enhanced human in a neon-lit alley.",
    "An alien landscape with strange flora and fauna.",
    "A steampunk airship soaring through the clouds.",
    "A dystopian society under oppressive surveillance.",
    "A retro-futuristic robot serving tea to humans.",
    "A time machine hidden in an old library.",

    // 3D model of any random object
    "A detailed 3D model of a vintage typewriter.",
    "A futuristic spaceship with sleek curves.",
    "A 3D-printed replica of the Eiffel Tower.",
    "A rotating model of a DNA double helix.",
    "A complex geometric shape with intersecting planes.",
    "A realistic 3D rendering of a dragon.",
    "A mechanical gear mechanism in motion.",
    "A stylized 3D model of a classic car.",
    "A miniature cityscape with tiny buildings.",
    "A detailed model of a human skull.",

    // Large random object (e.g., robot, car) made of toothpicks, stones, paper, etc.
    "A toothpick sculpture of a towering skyscraper.",
    "A stone mosaic depicting a mythical creature.",
    "A paper origami dragon with intricate folds.",
    "A toothpick-and-glue model of a vintage car.",
    "A stone castle built on a miniature island.",
    "A paper airplane with elaborate designs.",
    "A toothpick robot with movable joints.",
    "A stone sculpture of a majestic eagle.",
    "A paper cityscape with tiny windows",
    "A serene lakeside at dusk, with the last rays of the sun reflecting off the water",
    "An ancient library filled with towering bookshelves and dusty tomes",
    "A bustling city street at noon, alive with the sound of pedestrians and traffic",
    "A tranquil garden with a variety of flowers in full bloom",
    "A mysterious cave illuminated by the light of glowing crystals",
    "A snowy mountain peak under a clear blue sky",
    "A medieval castle courtyard during a vibrant renaissance fair",
    "A sandy beach with gentle waves lapping at the shore",
    "A vibrant coral reef teeming with colorful marine life",
    "An abandoned amusement park, with a rusting ferris wheel and silent roller coasters",
];

export default prompts;
